name: Update README all working days

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1-5' # Tous les jours de la semaine (lundi à vendredi) à midi
    - cron: '0 1 4 3 *'   # 4 mars à midi
    - cron: '0 1 31 10 *' # 31 octobre à midi
    - cron: '0 1 25 12 *' # 25 décembre à midi

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0   
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update README.md file
        run: |
          node index.js > README.md
        env:
          CI: true
      - name: Get Changes Since Last Commit
        id: file-changes
        uses: trilom/file-changes-action@v1.2.3
        with:
          githubToken: ${{ secrets.GH_TOKEN }}
          fileOutput: changes.txt
      - name: Append Changes to Change Log
        run: |
          touch changes.txt
          cat changes.txt >> CHANGELOG.md  # Append changes to your CHANGELOG.md file
          rm changes.txt  # Remove temporary changes.txt file
        if: steps.file-changes.outputs.files
      - name: commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: estebanmathia
          author_email: esteban.mathia@supinfo.com
          force: false
          signoff: false
          message: ':memo: README.md updated automaticaly'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Git Version
        id: versionning
        uses: codacy/git-version@2.8.0
        with:
          release-branch: main
          dev-branch: dev
          log-paths: ./
          minor-identifier: 'feat:'
          major-identifier: 'break:'
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ steps.versionning.outputs.version }}"
      - name: Notification on Discord
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          username: MyReadmeBot
          color: '#FFFF00'
          avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          description: New update du jour
          details: ''
          footer: New commit
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
