name: Update README all working days

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1-5' # Tous les jours de la semaine (lundi à vendredi) à midi
    - cron: '0 1 4 3 *'   # 4 mars à midi
    - cron: '0 1 31 10 *' # 31 octobre à midi
    - cron: '0 1 25 12 *' # 25 décembre à midi

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update README.md file
        run: |
          node index.js > README.md
        env:
          CI: true
      #- name: commit changes
      #  uses: EndBug/add-and-commit@v4
      #  with:
      #    author_name: estebanmathia
      #    author_email: esteban.mathia@supinfo.com
      #    force: false
      #    signoff: false
      #    message: ':memo: README.md updated automaticaly'
      #  env:
      #    # This is necessary in order to push a commit to the repo
      #    GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Set up Git
        run: |
          git config user.name "estebanmathia"
          git config user.email "esteban.mathia@supinfo.com"
      - name: commit changes
        run: |
          git add .
          git commit -m ":memo: README.md updated automatically"
          git push origin HEAD
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
